name: admin_page
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  hexcolor:
  cloud_firestore:
  firebase_core: 
  firebase_auth_web:
  google_sign_in_web:
  google_sign_in:
  provider:
  basic_utils:
  image_picker:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf



